version: "3"
services:
  backend:
    build: .
    image: backend
    ports: 
      - "3000:3000"
    container_name: backend
    environment:
      - MYSQL_DATABASE= int222db
      - MYSQL_USER= int222db
      - MYSQL_ROOT_PASSWORD= int222db
    volumes:
      - /home/INT222project/backendimg:/src/image_resource
    networks:
       project221:
          ipv4_address: 172.25.0.2
networks:
  default:
    external:
       name: project221
  project221:
    external: true
